### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by TheJaredWilcurt** [AustinGil/Vuetensils#105]
There should be a Vue 3 compatible version of Vuetensils. Not sure how it should be handled (new major version bump, or just two different branches).

**Comment by Stegosource** [comment]
Yeah, I was already prepping a major version bump anyway, so I think I'll add support there anyway. Im curious what doesnt work or where the gaps are though. V3 should be somewhat backwards compatible.

**Comment by patrickcate** [comment]
I believe Vue 3 no longer has filters.

**Comment by gwenf** [comment]
I'll be working on this this week. I'll update here as I find things and hopefully make a PR soon.

**Comment by Stegosource** [comment]
That would be awesome @gwenf. Thank you!

**Comment by gwenf** [comment]
Just want to post an update on this issue.
I've been trying out updating this library and I think we should wait for 2 things:

1. Migration build which should be out soon: https://v3.vuejs.org/guide/migration/introduction.html#breaking-changes
1. Vuepress to support Vue 3, which they are working on: https://github.com/vuepress/vuepress-next

**Comment by AustinGil** [comment]
Thanks for the update @gwenf. I was thinking about this recently as well. Been too busy with other stuff, but I've been doing more work with Vuetensils on a work project which is the best way for me to make some decisions about things. Whats missing, what could be better, etc.

**Comment by gwenf** [comment]
Update: Vuepress Next is in alpha 15 already. We can start migrating this soon.

**Comment by 2011sandeepraj** [comment]
Hello, Our inexperienced development team is about to decide between using Vue2 and Vue3 for a project in the next week. While most prefer Vue3, we are keeping a close eye on all of the Material design libraries out there including vuetensils. Is there an date when you think this Vuetensils support for Vue3 will be ready to use?

**Comment by AustinGil** [comment]
Hey, @2011sandeepraj, I dont have a date for support planned yet. I appreciate your support, but I want to also make sure you are aware this is not a Material design library. Are you sure you aren't thinking of something like Vuetify?

**Comment by 2011sandeepraj** [comment]
Thanks @AustinGil  Right! We are just looking at this library instead of vuetify as vuetify's support for vue 3 is out in Q3/Q4
We did look at PrimeVue as it is already supporting vue 3 but it does lack community support. Others like Quasar are also still under development. 
Do you have any other suggestions?

**Comment by lbineau** [comment]
Hello @AustinGil,
I'm starting a new project on Vue 3. 
Any plans for a Vuetensils beta version? :-)
Thank you.

**Comment by AustinGil** [comment]
Great question @lbineau. Im beginning my own migration to Vue 3 recently as well. I've added some features to Vuetensils for composition API support, but I'm still not sure how to migrate existing components without introducing breaking changes or having to maintain two codebases (if you know a way please let me know).

With my last round of changes in place, supporting Vue 3 is my next goal, so I'm hoping to get it squared away soon. Sorry I can't give an exact date.

**Comment by lbineau** [comment]
I'm still using Vue 3 as I was using Vue 2 without composition API, so it is very transparent for me to switch. That's obviously not the case for libraries, I totally get that.

In the latest 3.1 release core team introduced a Migration build https://v3.vuejs.org/guide/migration/migration-build.html to help people migrating libraries:
- Upgrading a Vue 2 application to Vue 3 (with limitations)
- Migrating a library to support Vue 3
- For experienced Vue 2 developers who have not tried Vue 3 yet, the migration build can be used in place of Vue 3 to help learn the difference between versions.

Not sure how helpful it will be but I really think there is a strong need for that tool. Very few libraries (especially small ones like yours) are available in Vue 3 and the adoption rate really depend on the ecosystem.

**Comment by AustinGil** [comment]
Thanks @lbineau. I saw that migration tool, but didn't know it worked for libraries as well. I've also come across Vue Demi which may do the trick https://github.com/vueuse/vue-demi. I definitely want to get V3 support in the next release cycle.

**Comment by AustinGil** [comment]
Vue 3 support should be ready to go

**Comment by lbineau** [comment]
I will give it a try for the only component I'm using on a Vue 3 project (Toggle).
Thanks for the hard work @AustinGil!
