### ISSUE TITLE
Vuetensils Logo

### ISSUE THREAD

**Issue by TheJaredWilcurt** [AustinGil/Vuetensils#106]
The current "logo" is really just the fork/knife emoji (🍴), the official Vue logo, then the hammer and wrench emoji (🛠️).

<p align="center"><img src="https://vuetensils.stegosource.com/static/logo.png" alt="Current Vuetensils logo"></p>

The concept behind the current logo is to convey that it is a Utility component library for Vue.js. The knife/fork are as a reference to the name "Utensils" also being used to refer to knives/spoons/forks.

@Stegosource Do you have any thoughts on what you would want in a logo, if someone in the community wanted to contribute one?

* * *

Some examples of existing logos from other Vue projects in the Vue ecosystem.

. | .
:-- | :--
![VueMastery](https://cdn-images-1.medium.com/max/952/1*TvOnUZVlpgu-UCWh2kBFEA@2x.png) | ![VueSchool](https://vueschool.io/img/logo/vueschool_logo_multicolor_negative.svg)
![VueStyleguidist](https://raw.githubusercontent.com/vue-styleguidist/vue-styleguidist/dev/assets/logo-withtext.png) | ![Vuetify](https://camo.githubusercontent.com/41759602ad091b02adf7b4986b55b0a870471b98/68747470733a2f2f63646e2e767565746966796a732e636f6d2f696d616765732f6c6f676f732f6c6f676f2e737667)
![VueSax](https://lusaxweb.github.io/vuesax/vuesax-logo-vertical.png) | ![Inkline](https://d33wubrfki0l68.cloudfront.net/b524a8e669681c46b2560311f7cc3e4ee2abf1f1/95711/images/logo-80.png)
![VueAwesome](https://raw.githubusercontent.com/vuejs/awesome-vue/master/assets/logo.svg) | ![Bootstrap-Vue](https://raw.githubusercontent.com/bootstrap-vue/bootstrap-vue/master/static/banner.png)
![Nuxt](https://camo.githubusercontent.com/06b2f979b4fbab8f1822cab69783700f0afa1f90/68747470733a2f2f6e7578746a732e6f72672f6d6574615f3430302e706e67) | ![VueMaterial](https://camo.githubusercontent.com/55e8a928e9fca0eeb4e7cb7836cb60dc05703c65/68747470733a2f2f7675656d6174657269616c2e696f2f6173736574732f6c6f676f2d636f6c6f722e706e67)
![VuePress](https://raw.githubusercontent.com/vuejs/vuepress/master/packages/docs/docs/.vuepress/public/hero.png) | ![iView](https://camo.githubusercontent.com/0f96ab8e2f2cb842287870ba1a4edfaddf66d2d1/68747470733a2f2f66696c652e697669657775692e636f6d2f6c6f676f2d6e65772e737667)

**Comment by Stegosource** [comment]
Yeah, you pretty much deconstructed my thinking exactly. This was something I just put together quickly. It got some folks that said they like it, but it's not something I'm hooked on. Why, you know someone? That would be cool. Open to whatever thoughts, but I do like the reference to "utensils" being utility components.

**Comment by TheJaredWilcurt** [comment]
**Logo idea:**

There is actually a utensil napkin folding pattern called "Ice cream cone" that gives a nice **V** shape, while holding utensils. Something around this idea could be used.

![vue](https://user-images.githubusercontent.com/4629794/94477749-4c36ff80-01a0-11eb-8144-918deff6d04c.jpg)
![vue-](https://user-images.githubusercontent.com/4629794/94477757-4e995980-01a0-11eb-819b-b130e2af9419.jpg)

**Comment by Stegosource** [comment]
Hahaha. Thats pretty cool. I wonder how well it would play with the Vue logo. Do you think we would still keep the reference to tools? Or just drop those?

**Comment by gwenf** [comment]
@Stegosource the tools seems extra to me. I like Jared's idea above which would be a good way to combine the 'V' shape of the Vue logo with utensils. I don't see any reason to add tools on top of that.

**Comment by patrickcate** [comment]
![vuetensials](https://user-images.githubusercontent.com/6277206/99159085-6755c400-26a7-11eb-9601-f090fac20c5c.jpg)

Here's one rough idea I had. Plays more on the utility/tools aspect.

**Comment by AustinGil** [comment]
Whoa. Super cool @patrickcate. Nice work. Do you think it's a good idea to include a fork and spoon to tie in the "utensils" idea?

What do you think @TheJaredWilcurt? It's different than your idea with the napkin, but it's pretty cool.

**Comment by ontoneio** [comment]
Took a stab a laying out a design. Really like the napkin and utensils direction suggested by @TheJaredWilcurt . Love any feedback.



![vuetensils-logo-sketch.jpg](https://user-images.githubusercontent.com/24515434/104142451-85226b00-5370-11eb-8cbc-fb69b213afe0.jpg)

**Comment by AustinGil** [comment]
That's pretty good @ontoneio. I like it. Let me see if I can make a vector version.

**Comment by AustinGil** [comment]
First pass. Thoughts?

![image](https://user-images.githubusercontent.com/4879075/104202166-6a3b0f80-53df-11eb-9c63-4884e9f345c8.png)

**Comment by ontoneio** [comment]
@AustinGil  I dig it, it's great start. 
I might be alone in this, but I would love to see the logo be a slight departure from the Vue logo itself.
Utilizing the colors and iconography to communicate we are part of  the Vue ecosystem or something more subtle.

The utensils are really strong shapes and I think work well. Definitely liking that direction, though I would prefer to depart from anything grey or cold metal like in the logo, as I don't think they quash well with the Green. Perhaps a white set of utensils with a stronger black outline.  Anyway I think this going the right direction.

I would love to take a stab at this in illustrator when I get some more time.

**Comment by AustinGil** [comment]
Yeah, I agree. But this was the best I could do before work and I had already spent way too much time playing with the pocket knife idea. I'll keep with the Vue colors, but we can leave the logo out of it :

**Comment by AustinGil** [comment]
@ontoneio What do you think about these:

**Comment by AustinGil** [comment]
@ontoneio what do you think about these? The one with the white utensils can also have the utensils be transparent. Wont make much difference on a white bg, but on other colors might be cool

![image](https://user-images.githubusercontent.com/4879075/104277223-53d29980-545b-11eb-82dc-110e826377f6.png)

**Comment by TheJaredWilcurt** [comment]
the fork looks really wide, like a pitch fork. doesn't look like an eating utensil

**Comment by gwenf** [comment]
I was just about to offer to hire someone for this, but looks like you are on the right track.
I really like the tri-color one with the white utensils.

What do you think about posting this on Twitter or somewhere and asking for public feedback?

**Comment by ontoneio** [comment]
I agree with @TheJaredWilcurt the fork looks a bit wide. 
I was hoping we could embellish the V shape a bit more perhaps with some of the colors from the Nuxt logo. I think it would work nice as a 4 color scheme.  Something like 3 shades of green and a white for contrast.  Like com patterns on the V to indicate it as something folded like a fancy cloth napkin. There's a subtle drop in the middle revealing more of a nice asymmetric but central balance of the utensils

See this example I through together off the existing.

![image](https://user-images.githubusercontent.com/24515434/104364770-eca0fd80-54cb-11eb-92ff-1bcca6de65dc.png)

**Comment by TheJaredWilcurt** [comment]
I would take these into Illustrator and trace them with the pen tool

![utensils](https://user-images.githubusercontent.com/4629794/104380938-c5f9bb80-54f9-11eb-89d8-b85a4305c216.png)

**Comment by AustinGil** [comment]
Updated the fork and added a bit of depth. I dont think I want to have too much going on with it though. How does this look?

![image](https://user-images.githubusercontent.com/4879075/104469612-8f5d8880-556d-11eb-8444-7b4a458d3bbb.png)

**Comment by ontoneio** [comment]
@AustinGil coming along real nice!
I hear you about not having it be to busy. I was just playing around. Though I like the newly added depth, I still think there is a lot of negative space used in the foreground. Perhaps something like this? Kinda hides the Vue logo in there a bit without being a dead copy. Something like a monogram on a cloth napkin?

![vuetensils-logo-v002](https://user-images.githubusercontent.com/24515434/104533714-c5c7f180-55c7-11eb-88d3-88b92612e86d.png)

**Comment by AustinGil** [comment]
This is looking pretty good. I still like the plain one better, but Im cool with a vote. Let's see which one @TheJaredWilcurt or @gwenf  like better and go with that one.

**Comment by gwenf** [comment]
I like the plain one better too, but @TheJaredWilcurt is much better at this stuff so I will defer to him.

**Comment by ontoneio** [comment]
As I am sitting here looking back at the designs I am starting to like the plain one more myself.
I switch my vote or withdrawal my entry. lol

**Comment by TheJaredWilcurt** [comment]
follow your heart
