### ISSUE TITLE
Add open and close events to modal and drawer

### ISSUE THREAD

**Issue by AustinGil** [AustinGil/Vuetensils#113]
Title says it all :)

**Comment by ontoneio** [comment]
See PR #119 

I wasn't sure if this is exactly what was meant, but I figured it couldn't hurt to try.
Really looking forward to contributing more to this project.

**Comment by AustinGil** [comment]
Yeah, thanks for this. I've been meaning to get more work done on it, but there are some other things on my plate. I appreciate any help I can get :)
