### ISSUE TITLE
VInput question

### ISSUE THREAD

**Issue by mgambill** [AustinGil/vuetensils#48]
Does the library support checkbox lists like the following?
https://vuejs.org/v2/guide/forms.html#Checkbox

**Comment by Stegosource** [comment]
Hi @mgambill, thanks for asking. There is a VInput component which can take a type of `checkbox`. You can see it in action here: https://vuetensils.stegosource.com/components/VInput.html#input-types

When you say checkbox lists, I'm not really sure what you mean. The example shows several HTML checkboxes that are bound to some values. This would work the same with Vuetensils, but there is currently not a way to have one component that manages many checkboxes. It is on the roadmap though.

So maybe if you can describe your use case, I can get a better idea of what you actually need.

**Comment by mgambill** [comment]
The current checkbox only supports true/false. Which is one use a secondary use is an array of values. Below is scenario I'm thinking about is similar to radio in that it takes an array but maps to a single array.

`<VInput type="checkboxlist" :options="['Microsoft','Apple','Google']" label="Please select brands you own" v-model="value" />`

with vue:
`
data(){
return value: ['Microsoft','Apple']
}
`

**Comment by Stegosource** [comment]
Yes. I've seen that sort of pattern before, and I agree it should be added. To answer your original question, it does not currently exist, but I will get to it :)

**Comment by AustinGil** [comment]
Well, this took me a while to get to, but I think it's in the project at this point :)
