### ISSUE TITLE
Offer to contribute (existing components)

### ISSUE THREAD

**Issue by Truemedia** [AustinGil/Vuetensils#55]
Hi,
I found this project and have my own idea for creating naked components for a while.

At the moment these are only used on a personal project and closed source, but I'd be willing to make them open source for the right project.

I'm wondering if I could contribute some of these, including:
- Qr code component
- Date/time/datetime component (render moment instance with easy to read formatting options)
- Version (output semver as formatted string)
- Copyright (Automatic copyright notice with current and optionally starting year)
- Heading (pick a heading level between 1 and 5)

Some of these components have a single dependency but excluding the QR component could be rewritten to have no dependencies if needed.

**Comment by brandonpittman** [comment]
These things all seem to be out of scope for Vuetensils. Maybe the copyright one…

**Comment by Truemedia** [comment]
Yeh is up to you, I don't want to overcomplicate the project. Just looking to contribute any existing work that would tie in nicely with the vision of the project aswell as even author new components.

**Comment by Stegosource** [comment]
Hey, thanks @Truemedia. Thanks for the interest, really appreciated. The goal for the library is to provide most of what a web app would need, but not necessarily everything under the sun. One thing that I definitely want to add is a date/time/datetime picker, so that may be a good place to start, however, I'm also trying to keep it dependency free (probably why I haven't already tackled that one). If that's something you would like to contribute, it would be welcomed :)

**Comment by Truemedia** [comment]
@Stegosource Yes I think date input/output would be good. I do know a few ways to do native date and time io without libraries so yeh could make a start on that

**Comment by somecallmejosh** [comment]
Would love to see an accessible date picker feature!

**Comment by Stegosource** [comment]
@Truemedia Are you still interested in contributing the datepicker idea?

**Comment by Truemedia** [comment]
> @Truemedia Are you still interested in contributing the datepicker idea?

I am still interested just short on time at the moment due to work/personal life. I should have a lot more time on my hands closer to just before summer begins.

**Comment by Stegosource** [comment]
No worries. Just doing some maintenance on the issues :)
